apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: three-tier
  labels:
    app: backend
    tier: api
  annotations:
    kubernetes.io/change-cause: "initial deployment v1.o"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: backend
        tier: api
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3000"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: backend-sa

      initContainers:
        - name: wait-for-postgres
          image: busybox:1.35
          command:
            - 'sh'
            - '-c'
            - |
              until nc -z postgres-svc 5432; do
                echo "Waiting for PostgreSQL..."
                sleep 3
              done
              echo "PostgreSQL is Ready!"

      containers:
        - name: backend
          image: hashicorp/http-echo:alpine
          args: ["-text={\"status\":\"healthy\",\"service\":\"backend-api\",\"version\":\"1.0.0\"}"]
          ports:
            - name: http
              containerPort: 5678

          envFrom:
            - configMapRef:
                name: backend-config

          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: JWT_SECRET
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace

          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "300m"

          startupProbe:
            httpGet:
              path: /
              port: 5678
            failureThreshold: 15
            periodSeconds: 2

          readinessProbe:
            httpGet:
              path: /
              port: 5678
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /
              port: 5678
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
      
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: backend
---
apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  namespace: three-tier
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
    - name: http
      port: 3000
      targetPort: 5678
