apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend-sa
  namespace: three-tier
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend-sa
  namespace: three-tier
automountServiceAccountToken: false
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: backend-role
  namespace: three-tier
rules:
  - apiGroups: [""]
    resources: ["ConfigMap"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: backend-rolebinding
  namespace: three-tier
subjects:
  - kind: ServiceAccount
    name: backend-sa
    namespace: three-tier
roleRef:
  kind: Role
  name: backend-role
  apiGroup: rbac.authorization.k8s.io
